package bento.tiago.visa;

public enum Status {
	VERIFICAR_VALIDADE, 
	ARQUIVO_INVALIDO, 
	BUSCAR_VENCIMENTO, 
	BUSCAR_TOTAL_FATURA, 
	BUSCAR_TRANSACOES, 
	BUSCAR_TOTAIS, 
	BUSCAR_DOLAR, 
	FIM_IMPORTACAO;
}
